In [54]:
# 4. Python code to access the first row of the array:

array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
       [9, 10, 11, 12]]
first_row = array[0]
  

In [55]:
# 5. To access the element at the third row and fourth column:
  
array[2][3]

12

In [56]:
# 6. Code to extract all odd-indexed elements from the array:

# Extracting all odd-indexed elements
odd_indexed_elements = [row[1::2] for row in array]

print("Odd-indexed elements:")
print(odd_indexed_elements)
 

Odd-indexed elements:
[[2, 4], [6, 8], [10, 12]]


In [57]:
# 7. Generating a random 3x3 matrix with values between 0 and 1:

random_matrix = np.random.rand(3, 3)
random_matrix 

array([[0.07092229, 0.97412747, 0.17041684],
       [0.11711593, 0.67942428, 0.99090045],
       [0.97549962, 0.54744589, 0.19259144]])

In [58]:
# 9. Code to increase the dimension of the array:
   
increased_dimension_array = np.expand_dims(array, axis=0)
increased_dimension_array 

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [59]:
# 10. Transposing the array:
    
transposed_array = np.transpose(array)
transposed_array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [60]:
# 11. Performing operations on matrices A and B:
    
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = A * B

# Matrix multiplication
matrix_multiplication = np.dot(A, B.T)

# Addition
addition = A + B

# Subtraction
subtraction = B - A

# Division
division = np.divide(B, A)

In [61]:
# 14. The `np.reshape` function is used to change the shape of an array without changing its data. It allows us to specify the new shape of the array.

# Given array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Define the new shape
new_shape = (2, 6)  # For example, reshaping to a 2x6 array

# Reshape the array
reshaped_array = np.reshape(array, new_shape)

print("Reshaped array:")
print(reshaped_array)


Reshaped array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
